services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - ./etc/mongo/challenge/user/init.js:/docker-entrypoint-initdb.d/joinup-challenge-init.js:ro
